<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-DGarcia-A01086411/blob/main/Semana_7_Data_Analysis_with_Python_Modulo_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#David Eduardo Garcia Reyes - A01086411

##Actividad Semana 7 - Data Analysis with Python
##Modulo 4

#**Teoria**

#Evidencia Graded Review Questions - Modulo 4

In [1]:
#Model Development

In [2]:
#Importar las librerias necesarias para el laboratorio
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Definir link para archvio de base de datos de descarga y cargar dataframe
path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/automobileEDA.csv'
df = pd.read_csv(path)
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

In [4]:
#1. Linear Regression and Multiple Linear Regression

In [5]:
#Importar modulos para regresion linear
from sklearn.linear_model import LinearRegression

In [6]:
#Crear objeto de regresion linear
lm = LinearRegression()
lm

LinearRegression()

In [8]:
#Utilizar highway-mpg para ver si nos ayuda a predecir el precio
X = df[['highway-mpg']]
Y = df['price']
lm.fit(X,Y)

LinearRegression()

In [9]:
#Mostrar una prediccion
Yhat=lm.predict(X)
Yhat[0:5]

array([16236.50464347, 16236.50464347, 17058.23802179, 13771.3045085 ,
       20345.17153508])

In [10]:
#Valor intercept a
lm.intercept_

38423.3058581574

In [11]:
#Valor slope b
lm.coef_

array([-821.73337832])

In [12]:
#Crear objeto de regresion linear llamado lm1
lm1 = LinearRegression()
lm1

LinearRegression()

In [13]:
#Utilizar engine-size para ver si nos ayuda a predecir el precio
lm1.fit(df[['engine-size']], df[['price']])
lm1

LinearRegression()

In [15]:
#Valor intercept a
lm1.intercept_

array([-7963.33890628])

In [16]:
#Valor slope b
lm1.coef_

array([[166.86001569]])

In [ ]:
#Ecuacion de la prediccion
Yhat = -7963.34 + 166.86 * X
Price = -7963.34 + 166.86 * df['engine-size']